### PR TITLE
Update to SuiteSparse:GraphBLAS v8.0.0

### PR DESCRIPTION
**Pull request by eriknw**

### CODE REVIEW

**Comment by DrTimothyAldenDavis** [comment]
Let me know if you'd like to talk sometime about the new JIT and how it might be used via Python.

**Comment by DrTimothyAldenDavis** [comment]
You can see I've updated some enum values, for my get/set methods.  I did that so I can use the same values as GxB extentions to the new GrB_Option_Field.  My next goal is to draft the new GrB_get/set methods.

**Comment by eriknw** [comment]
Thanks Tim. I'll let you know if we have any difficulties (I'm surprised you didn't have any beta releases for 8.0.0). I've heard you talk about the JIT many, many times, but maybe other people would like to take you up on the offer.

**Comment by DrTimothyAldenDavis** [comment]
I decided to go straight to v8.0.0 without a preceding beta because I've gotten lots of feedback already with the many 8.0.0.draft* pre-releases.  Hopefully that won't be a problem.  I'll likely post a v8.0.1 soon anyway, once the JIT gets exercised. I don't expect to see any bugs but there might be features in the get/set controls for the JIT that some applications need.

**Comment by DrTimothyAldenDavis** [comment]
In addition, I wanted a stable v8.0.0 so I could use it to start implementing the draft GrB_get/set in the draft C API proposal.  There are lots of get/set features for the JIT and I didn't want to work on two things at the same time.

**Comment by DrTimothyAldenDavis** [comment]
OK ... mostly stable ( https://github.com/DrTimothyAldenDavis/GraphBLAS/issues/215 ).  Looks like I will post a v8.0.1 soon.

**Pull request merged**
