### PR TITLE
Update to SuiteSparse:GraphBLAS 8.2.1

### LINKED ISSUE #109: Artifacts not uploaded to PyPI upon release
I think this change made in #105 might not allow the upload to occur when doing a release:
https://github.com/GraphBLAS/python-suitesparse-graphblas/commit/84e41c2deab8f1e2cbe3a4aac53a7d84e92c9552#diff-75627befeafda60a526c116b32f6fdef9bf57bcf456f840d7592c1d6f13facb4R196

I will upload the 8.2.0.1 artifacts to PyPI manually (once the download finishes 🤣)

### PR DESCRIPTION
**Pull request by eriknw**
Also, hopefully fix #109 by changing release trigger to "published", not "created".

### CODE REVIEW

**Comment by alugowski** [comment]
Good catch! So the workflow was being triggered on release "create" but the upload was only enabled for "publish".

**Comment by eriknw** [comment]
Yup! I think "published" is the right one to use, which you reasonably did in the if condition:
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release

New release coming up 🤞

**Comment by eriknw** [comment]
Why? 😭 
```
 build/temp.macosx-11.0-arm64-cpython-38/suitesparse_graphblas._graphblas.c:570:10: fatal error: 'GraphBLAS.h' file not found
```
https://github.com/GraphBLAS/python-suitesparse-graphblas/actions/runs/6513170637/job/17692251398?pr=110#step:8:1615

**Comment by eriknw** [comment]
I see, the `brew fetch` failed in `add_arm_to_libomp_dylib.sh`. Retry should hopefully fix.

**Comment by eriknw** [comment]
@alugowski do you know how to add retries to brew commands? A quick search left me even more confused. Network in CI can be flaky, so it would be nice to make our commands more resilient.

**Comment by eriknw** [comment]
Even though it's a little slower and adds some noise, I really like building wheels for PRs!

**Comment by alugowski** [comment]
> @alugowski do you know how to add retries to brew commands? A quick search left me even more confused. Network in CI can be flaky, so it would be nice to make our commands more resilient.

Looks like the `--retry` switch does that:
```
       --retry
              Retry if downloading fails or re-download if the checksum of a previously cached version no longer matches. Tries at most 5 times with exponential backoff.
```

We can also add a "|| exit 1" on the script invocation to fail fast. I can make a PR.

**Comment by alugowski** [comment]
> Even though it's a little slower and adds some noise, I really like building wheels for PRs!

Agreed!

**Comment by alugowski** [comment]
I recently discovered you can add input options to manual workflow dispatch. So I experimented with such an input to control PyPI upload:

image

Would you like it to be added here? That way if a workflow run fails for an ephemeral reason then it can be rerun manually.

**Comment by alugowski** [comment]
> @alugowski do you know how to add retries to brew commands? A quick search left me even more confused. Network in CI can be flaky, so it would be nice to make our commands more resilient.

https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/111

**Comment by alugowski** [comment]
> I recently discovered you can add input options to manual workflow dispatch. So I experimented with such an input to control PyPI upload:
> image
> 
> Would you like it to be added here? That way if a workflow run fails for an ephemeral reason then it can be rerun manually.

https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/112

**Pull request merged**
