### PR TITLE
Update to SuiteSparse:GraphBLAS 9.1.0

### PR DESCRIPTION
**Pull request by eriknw**

### CODE REVIEW

**Comment by eriknw** [comment]
@alugowski @michelp I made some progress updating `python-suitesparse-graphblas` to 9.1.0 (yes I know 9.2.0 was just released).

The wheel builds are failing (hooray for tests!), and I'm wondering if either of you could help take a look (I'm busy traveling this week and next week).

Changes:
- It looks like "GraphBLAS.h" moved from "include/" to "include/suitesparse", and we need to update the wheel building scripts to look here
- It looks like `add_arm_to_libomp_dylib.sh` script may no longer be necessary
- SuiteSparse:GraphBLAS updated how it builds (maybe in 8.3?), and we need to update too. Maybe this means using `cmake` instead of `make` as was done here: https://github.com/conda-forge/graphblas-feedstock/pull/71

**Comment by alugowski** [comment]
I can take a look this weekend.

To get rid of the macos OMP hack we'll need to use the new runners as per https://github.com/actions/runner-images/issues/9254
We may need to keep the current one for x86, too, since we get omp from brew and AFAIK it'll still only install the native arch. That's ok, I purposely kept the two macos arches separate in anticipation of this :)

**Comment by alugowski** [comment]
FYI I've had good experience using [scikit-build-core](https://github.com/scikit-build/scikit-build-core) for cmake-based projects. Better try fixing what we have first, but might be worth considering for any future refactor.

**Comment by alugowski** [comment]
Would it be possible to make this into a branch on this repo so I'm able to add commits?

**Comment by DrTimothyAldenDavis** [comment]
The latest updates to the cmake build system for GraphBLAS (and all of SuiteSparse) is very stable now. So any changes you need to make would also work for a long time, for future updates to my codes.

**Comment by eriknw** [comment]
> Would it be possible to make this into a branch on this repo so I'm able to add commits?

Done. `update9.1.0` branch

**Comment by alugowski** [comment]
> > Would it be possible to make this into a branch on this repo so I'm able to add commits?
> 
> Done. `update9.1.0` branch

Great! I pushed changes to that branch that appear to work. Sorry I don't think it's possible to update the PR to be from that branch instead of the one from your fork, so I opened a new PR https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/128 Let's move discussion there.

**Pull request closed without merging**
