### PR TITLE
Support building from source with user-specified GraphBLAS

### PR DESCRIPTION
**Pull request by alugowski**
Look for GraphBLAS first in GraphBLAS_ROOT env var, if empty then fallback to current paths.

using `GraphBLAS_ROOT` because that's what CMake expects when building against GraphBLAS in C++.

fixes https://github.com/GraphBLAS/python-suitesparse-graphblas/issues/79

### CODE REVIEW

**Comment by eriknw** [comment]
Thanks @alugowski! I'm going to give this a try locally and will let you know how it goes.

Btw, we do squash merges by default, so there is little need to rebase and force push to change history (but you can still do so if you want).

**Comment by eriknw** [comment]
Great, this works for me!

The graphblas shared objects also need to be findable _at runtime_. If SuiteSparse:GraphBLAS is installed in a non-standard location, this probably requires `LD_LIBRARY_PATH` to be set appropriately. I'm not sure if this is worth mentioning in the readme (if a user is compiling from source, they probably know this).

**Comment by eriknw** [comment]
Thanks for the quick update, this looks great to me!

I'd rather leave worrying about static linking for another day ;)

Merging and then doing an alpha release to test things out 🤞 🚀

**Comment by alugowski** [comment]
Sounds good!

**Pull request merged**
