### PR TITLE
Process v741 branch with GB_PUBLIC as the empty string

### PR DESCRIPTION
**Pull request by eriknw**

### CODE REVIEW

**Comment by eriknw** [comment]
Thanks @DrTimothyAldenDavis, it helps having a branch to target.

I've updated this PR so that `GB_PUBLIC` could be removed entirely from GraphBLAS.h.

Now I'm waiting to see whether CI passes...

**Comment by eriknw** [comment]
Yup, we're all good. Tests passing with your v741 branch :tada:

**Comment by DrTimothyAldenDavis** [comment]
Great!  I will delete GB_PUBLIC.

**Comment by DrTimothyAldenDavis** [comment]
Note that I have a new macro, GB_GLOBAL, which is necessary for the global data objects (predefined GrB_Types, ops, monoids, semirings, descriptors, etc).

**Review by DrTimothyAldenDavis — APPROVED** [review]

**Pull request merged**
